### ISSUE TITLE
Float comparison in 4.0.8

### ISSUE THREAD

**Issue by donatj** [sebastianbergmann/comparator#104]
In 4.0.7 and prior checking the equality of `1/3` vs `1 - 2/3` came out as true, upgrading to 4.0.8 however it now declares

> SebastianBergmann\Comparator\ComparisonFailure : Failed asserting that 0.33333333333333337 matches expected 0.3333333333333333

```php
$comparatorFactory = ComparatorFactory::getInstance();
$comparator = $comparatorFactory->getComparatorFor(1/3, 1 - (2/3));

$comparator->assertEquals(1/3, 1 - (2/3));
```

I could see this being an intentional change as it's arguably "more correct" but seems like a pretty major change for a 3rd point release.

**Comment by sebastianbergmann** [comment]
This was discussed in https://github.com/sebastianbergmann/phpunit/issues/4967, https://github.com/sebastianbergmann/comparator/pull/99, and https://github.com/sebastianbergmann/comparator/pull/102.
