### ISSUE TITLE
[Warning] Uninitialized string offset -1 at src/ScalarComparator.php:139

### ISSUE THREAD

**Issue by bastienho** [sebastianbergmann/comparator#118]
Since version 6.2.0, I got this error in codeception when trying to: `$I->seeResponseIsJson();`

```
[Warning] Uninitialized string offset -1 at /.../vendor/sebastian/comparator/src/ScalarComparator.php:139
```

**Comment by staabm** [comment]
@bastienho could you provide a reduced reproducing example?

**Comment by staabm** [comment]
just found a reproduction myself in https://github.com/sebastianbergmann/comparator/pull/119

thanks for the report
