### ISSUE TITLE
Blank diff output of NumericComparator

### ISSUE THREAD

**Issue by olegrom32** [sebastianbergmann/comparator#25]
The following assertion produces blank output:
$this->assertEquals(1, 0);

**Output**
There was 1 failure:

1) Test: Run
 Test  Test.php:testRun
`- Expected | + Actual`

**Expected output**
There was 1 failure:

1) Test: Run
 Test  Test.php:testRun
`- Expected | + Actual
-1
+0
`

ComparisonFailure exception should be provided with expectedAsString and actualAsString values (https://github.com/sebastianbergmann/comparator/blob/master/src/NumericComparator.php#L61) but it isn't.
As a result ComparisonFailure::getDiff() produces blank output:
https://github.com/sebastianbergmann/comparator/blob/master/src/ComparisonFailure.php#L114

**Comment by olegrom32** [comment]
Okay, the problem seems to be different. There should actually be no diff in case of numbers. There is an error message 'Failed asserting that %s matches expected %s' but it is not displayed anyway.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.
