### ISSUE TITLE
Project state (alive?)

### ISSUE THREAD

**Issue by Ovsyanka** [sebastianbergmann/comparator#54]
Hello!

I see here some issues (one of them mine) that didn't det any reply for years and now they just become closed without any solution or commentary why it will not be fixed/changed/whatever. For example #21.

How that happened? I saw some activity like a month ago, so this project doesn't look dead.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/comparator/issues/21#issuecomment-389272870 gave you seven days notice to provide the feedback that the issue is still relevant. Simply comment on https://github.com/sebastianbergmann/comparator/issues/21, no need to open a new issue like this one.

**Comment by Ovsyanka** [comment]
This question was not only about my issue, but about all of closed issues without your response.

I really appriciate all your work and this is not a claim(?) or something.

I just want to know why it happened to be able to act properly. Seems like I (or others) had to remember you about the issues. But when? After a week from start, a month, a year? I thought that you see them in the list of open issues and know that you didn't answer yet.
