### ISSUE TITLE
ArrayComparator ignores order - Part 2

### ISSUE THREAD

**Issue by dpauli** [sebastianbergmann/comparator#57]
As in https://github.com/sebastianbergmann/comparator/issues/44 mentioned the *ArrayComparator* ignore the order of two arrays, also if the attribute ```$canonicalize = false``` is set.

**Comment by 1blankz7** [comment]
There is a test for your use case so I think it is intended.

See: https://github.com/sebastianbergmann/comparator/blob/5de4fc177adf9bce8df98d8d141a7559d7ccf6da/tests/ArrayComparatorTest.php#L47

**Comment by luckydonald** [comment]
Fixed now?

**Comment by dpauli** [comment]
@sebastianbergmann Is fixed?

**Comment by sebastianbergmann** [comment]
There is nothing to fix here as @1blankz7 explained in https://github.com/sebastianbergmann/comparator/issues/57#issuecomment-419372641.

If you consider two associative arrays that have the same keys and the same values associated with these keys but a different order of elements to be different (I do not, the code does not) then you need to implement a custom comparator and use that.

**Comment by luckydonald** [comment]
But isn't the definiton of `equal` wrong here?
There should be a way to make sure they are actually the same order.

Take for example this completely constructed code:
```php
$html = [
  "h1" => "Greetings",
  "p" => "How are you today?"
]
for ($html as $tag => $content) {
  echo "<$tag>$content</$tag>";
}
```

One would output:
```html
<h1>Greetings</h1>
<p>How are you today</p>
```
> ### Greetings
> How are you today


But if the equal test ignores order, we might end up with:

```html
<p>How are you today</p>
<h1>Greetings</h1>
```
> How are you today
> ### Greetings

----

What is the intended way to check that `$html` is correct here?

**Comment by dpauli** [comment]
And how should the `$canonicalize = false` work? This attribute forces to be in correct order.

**Comment by luckydonald** [comment]
I mean, having `$canonicalize = true` (default), ignoring the order makes perfectly sense.

However, if `$canonicalize` is explicitly changed to `false`, It should allow us to really compare the values.

**Comment by luckydonald** [comment]
I mean the description says:
```php
/**
 * @param $canonicalize bool  Arrays are sorted before comparison when set to true
 */
```
