### ISSUE TITLE
comparation fails for 0 = NULL

### ISSUE THREAD

**Issue by parti-zanu** [sebastianbergmann/comparator#59]
https://github.com/sebastianbergmann/comparator/blob/c9eb293d22c2f16b1304281538b7408210a41585/src/ScalarComparator.php#L75

`if ($expectedToCompare != $actualToCompare) `

will fail for

$expectedToCompare is **int(0)**
$actualToCompare is **NULL**

meaning assertEquals(0, NULL) returns OK

EDIT:

ScalarComparator's assertEquals() is used by cakePHP's integration test assertSession() when testing for a NULL value variable like 

```
    public function test_null_is_zero()
    {
        $this->session(['lastErrorCode' => NULL]);
        $this->get('/');
        $this->assertSession((int)0, 'lastErrorCode');
    }
```

meaning this is not the same bug as #29

**Comment by sebastianbergmann** [comment]
`assertEquals()` encapsulates the behaviour of PHP's `==` operator.

```
php -a
Interactive shell

php > var_dump(0 == null);
php shell code:1:
bool(true)
```
