### ISSUE TITLE
ArrayComparator#assertEquals(), canonicalizing stops it from comparing array keys

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/comparator#77]
When using the canonicalize option both expected and actual arrays get sorted, and keys are removed, which causes comparison to be ok even if keys were not equal.

If canonicalize is set to false, comparison fails if keys are not equal.

![image](https://user-images.githubusercontent.com/590751/71373016-9b5a5f00-2594-11ea-80d3-3535bf7ba721.png)

**Comment by mgleska** [comment]
This issue is solved by issue #112 and PR #113.
