### ISSUE TITLE
DOMNodeComparator fails if Node has no Document

### ISSUE THREAD

**Issue by thled** [sebastianbergmann/comparator#86]
Some of my tests fail since this Commit: https://github.com/sebastianbergmann/comparator/commit/8e77ef2597d0303e197b76da26aa6bedc003b77d#diff-0665d25cb8db14b20881e327fe1ca491

It seems like the declaration of strict types changed that the function `nodeToText()` cannot handle `DOMNode`s that have no `DOMDocument`.

Is this intended?

I mean I can fix it by creating `DOMDocument`s and then the `DOMNode`s in my failing tests but should this be necessary?

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by thled** [comment]
Thank you for the fast response!

I am having trouble to create a minimal, self-contained test case. Since my setup where the issue occures is a Symfony project with the Bridge Component to PHPUnit and I use Prophecy for mocking. It seems like Prophecy is part of the issue because if I use the PHPUnit mocking the issue does not occure.
