### ISSUE TITLE
DateTimeComparator is invalid

### ISSUE THREAD

**Issue by WinterSilence** [sebastianbergmann/comparator#96]
1. Required version of PHP  moved up, but code not updated yet(partially fixes by PR #95)
2. `DateTimeComparator::assertEquals()` calls `setTimezone()`, but `DateTimeInterface` not declare this method

**Comment by sebastianbergmann** [comment]
Can you elaborate what bumping the PHP version requirement has to do with the changes you propose in #95 and/or the issue you report here? Thanks!

**Comment by sebastianbergmann** [comment]
I am sorry, but what you're saying does not make sense to me.

**Comment by WinterSilence** [comment]
@sebastianbergmann `DateTimeInterface` added in PHP 5.5, after PHP 5.5 no reason to check `($actual instanceof DateTime || $actual instanceof DateTimeInterface)`

**Comment by sebastianbergmann** [comment]
It's not invalid, just not as good as could be today.

**Comment by WinterSilence** [comment]
@sebastianbergmann where I'm say it's invalid? Invalid 2.

**Comment by sebastianbergmann** [comment]
The title of this issue is "DateTimeComparator is invalid".

**Comment by WinterSilence** [comment]
@sebastianbergmann 
> partially fixes by PR https://github.com/sebastianbergmann/comparator/pull/95)

this issue not description to PR #95 

> The title of this issue is "DateTimeComparator is invalid".

is it's true? yes, it is

**Comment by sebastianbergmann** [comment]
I am sorry, but I am not in the mood for being trolled.

**Comment by WinterSilence** [comment]
@sebastianbergmann I'm not troll you. Ignoring can't solve problem.
